{
 "title": "WAN Sizing Dashboard",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "98th Percentile WAN usage (No Compression)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "Mbits",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(\n  GROUP_CONCAT(WriteMbps ORDER BY WriteMbps SEPARATOR ','),\n   ',', 98/100 * COUNT(*) + 1), ',', -1) AS DECIMAL) AS '95th Per WAN Usage'\nFrom throughput;"
    }
   ]
  },
  {
   "title": "98th Percentile WAN usage (50% compression)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "Mbits",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n (CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(\n  GROUP_CONCAT(WriteMbps ORDER BY WriteMbps SEPARATOR ','),\n   ',', 98/100 * COUNT(*) + 1), ',', -1) AS DECIMAL) )* .5 AS '98th Per WAN Usage'\nFrom throughput;"
    }
   ]
  },
  {
   "title": "98th Percentile WAN usage (70% compression)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "Mbits",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n (CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(\n  GROUP_CONCAT(WriteMbps ORDER BY WriteMbps SEPARATOR ','),\n   ',', 98/100 * COUNT(*) + 1), ',', -1) AS DECIMAL) )* .3 AS '98th Per WAN Usage'\nFrom throughput;"
    }
   ]
  },
  {
   "title": "WAN Sizing Graph",
   "type": "graph",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "Mbits" }
   ],
   "targets": [
    {
     "rawSql": "SELECT time as time, WriteMbps as \"WAN-No-Compression\" FROM `throughput` GROUP By time,WriteMbps\n"
    },
    {
     "rawSql": "SELECT time as time, (WriteMbps *.5) as \"WAN-50%-Compression\" FROM `throughput` GROUP By time,WriteMbps\n"
    },
    {
     "rawSql": "SELECT time as time, (WriteMbps *.3) as \"WAN-70%-Compression\" FROM `throughput` GROUP By time,WriteMbps"
    }
   ]
  }
 ]
}