{
 "title": "Zerto Public Cloud Sizing Dashboard",
 "time": { "from": "now-30d", "to": "now" },
 "panels": [
  { "title": "Customer Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Account Information",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT Customer, AM, SE, SiteName from accountinfo"
    }
   ]
  },
  {
   "title": "Configed VM CPU / Memory",
   "type": "table",
   "description": "This table shows the current configured CPU count and Memory Size for each powered on virtual machine",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "rawSql": "SELECT\n  VMName as \"VM Name\",\n  NumCPU as \"Num CPUs\",\n  MemSize / 1024 as \"Memory Size (GB)\"\nFROM vminfo\nORDER BY \"VMName\" ASC"
    }
   ]
  },
  {
   "title": "Monitored VMs",
   "type": "singlestat",
   "description": "Average Write Rate for All Monitored VMs",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) FROM `vms` WHERE `monitor` LIKE 'Y'\n"
    }
   ]
  },
  {
   "title": "IOPS samples > 10000 IOps",
   "type": "singlestat",
   "description": "Average Write Rate for All Monitored VMs",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT COUNT(*)  FROM `stats` WHERE `IOPSWriteAvg` > 10000\n"
    }
   ]
  },
  {
   "title": "Average MB/s Write Rate",
   "type": "singlestat",
   "description": "Average Write Rate for All Monitored VMs",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 8 },
   "format": "MBs",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT datestamp as time, (SUM(KBWriteAvg) / 1024) as WriteMBps FROM `stats` GROUP By datestamp\n"
    }
   ]
  },
  {
   "title": "Estimated ZCAs Required",
   "type": "singlestat",
   "description": "This is the number of ZCAs estimated based on Write Throughput and 50% WAN Compression",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 8 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "SELECT\n CEIL((CAST(SUBSTRING_INDEX(SUBSTRING_INDEX(\n  GROUP_CONCAT(WriteMbps ORDER BY WriteMbps SEPARATOR ','),\n   ',', 98/100 * COUNT(*) + 1), ',', -1) AS DECIMAL)  * .5 / 8 / 50)) AS 'ZCA Estimate'\nFrom throughput;\n"
    }
   ]
  },
  { "title": "VM Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "Total Throughput MB/s of Monitored VMs",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT datestamp as time, (SUM(KBWriteAvg) / 1024) as WriteMBps FROM `stats` GROUP By datestamp\n"
    }
   ]
  },
  { "title": "VM Disk Activity Graphs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Total Write IOps for Monitored VMs",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "rawSql": "SELECT datestamp as time, SUM(IOPSWriteAvg) as IOps, AVG(writeIOAvgKB) as IOSizeKB FROM `stats` GROUP By datestamp\n"
    }
   ]
  }
 ]
}